spring:
  application:
    name: usermanagementservice

    datasource:
      url: dbc:mysql://localhost:3306/fnb_intelligent_bank_usermanagement
      username: root
      password: 1234
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQLDialect

app:
  super-admin:
    email: ${SUPER_ADMIN_EMAIL:admin@banking.com}
    first-name: ${SUPER_ADMIN_FIRSTNAME:super}
    last-name: ${SUPER_ADMIN_LASTNAME:Admin}
    id-number: ${SUPER_ADMIN_ID:9999999999999}
    initial-password: ${SUPER_ADMIN_PASSWORD:SuperAdmin@123}